# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introduction to Computational Genomics
description:      'From keyboards to genomes'
url:              https://owensgl.github.io
baseurl:          /intro-genomics
email:            grego@uvic.ca
feedbackurl:      
author:
  name:           'Greg Owens'
  url:            https://owensgl.github.io/

github:
  repo:           https://github.com/owensgl/intro-genomics
  #               Be sure the 'Issues' feature is activated in 'Settings'

plugins:
  - jekyll-sitemap 
